image: hashicorp/terraform

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - terraform init
              - terraform validate
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
        - step:
              name: "Cx KICS"
              script:
                  - |
                    apk add curl
                    kics scan --cloud-provider aws --report-formats "junit" --exclude-severities info,low --ignore-on-exit results -p ${PWD} -o ${PWD}
                    export token=$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$client_id\",\"client_secret\": \"$client_secret\" }" https://xray.cloud.getxray.app/api/v1/authenticate| tr -d '"')
                    curl -H "Content-Type: text/xml" -H "Authorization: Bearer $token" --data @junit-results.xml "https://xray.cloud.getxray.app/api/v1/import/execution/junit?projectKey=DD&revision=1.0"

              artifacts:
                  - results.json
              image: checkmarx/kics:latest
  branches:
    main:
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
        - step:
              name: "Cx KICS"
              script:
                  - |
                    apk add curl
                    kics scan --cloud-provider aws --report-formats "junit" --output-path test-results --exclude-severities info,low --ignore-on-exit results -p ${PWD} -o ${PWD}
                    export token=$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$client_id\",\"client_secret\": \"$client_secret\" }" https://xray.cloud.getxray.app/api/v1/authenticate| tr -d '"')
                    curl -H "Content-Type: text/xml" -H "Authorization: Bearer $token" --data @junit-results.xml "https://xray.cloud.getxray.app/api/v1/import/execution/junit?projectKey=DD&revision=$BITBUCKET_COMMIT&fixVersion=1.0"
              artifacts:
                  - junit-results.xml
              image: checkmarx/kics:latest
        - step:
            name: Deploy to Production
            deployment: Production
            trigger: manual
            script:
              - terraform init
              - terraform plan
              - terraform apply -auto-approve

