image: hashicorp/terraform

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - terraform init
              - terraform validate
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1
        - step:
              name: "Cx KICS"
              script:
                  - |
                    apk add curl
                    kics scan --cloud-provider aws --report-formats "junit" --exclude-severities info,low --ignore-on-exit results -p ${PWD} -o ${PWD}
                    export token=$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$client_id\",\"client_secret\": \"$client_secret\" }" https://xray.cloud.getxray.app/api/v1/authenticate| tr -d '"')
                    curl -H "Content-Type: text/xml" -H "Authorization: Bearer $token" --data @junit-results.xml "https://xray.cloud.getxray.app/api/v1/import/execution/junit?projectKey=DD&revision=1.0"`
              artifacts:
                  - results.json
              image: checkmarx/kics:latest
  branches:
    feature/*:
        - step:
            name: Security Scan
            script:
              - pipe: atlassian/git-secrets-scan:0.5.1
        - step:
              name: "KICS"
              script:
                  - |
                    apk add curl
                    apk add jq
                    kics scan --cloud-provider aws --report-formats "junit" --output-path test-results --exclude-severities info,low --ignore-on-exit results -p ${PWD} -o ${PWD}
                    export token=$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$client_id\",\"client_secret\": \"$client_secret\" }" https://xray.cloud.getxray.app/api/v1/authenticate| tr -d '"')
                    export ISSUE_KEY=$(curl -H "Content-Type: text/xml" -H "Authorization: Bearer $token" --data @junit-results.xml "https://xray.cloud.getxray.app/api/v1/import/execution/junit?projectKey=DD&revision=$BITBUCKET_COMMIT&fixVersion=1.0" | jq .key | tr -d '"')
                    curl -u $jira_user:$jira_token -H "Content-Type: application/json" -X PUT --data "{ \"fields\": { \"summary\": \"Kics results - pipeline $BITBUCKET_BUILD_NUMBER\", \"description\": \"Project: $BITBUCKET_PROJECT_KEY\nBranch: $BITBUCKET_BRANCH\nCommit hash: $BITBUCKET_COMMIT \" } }" https://collabinfra.atlassian.net/rest/api/2/issue/$ISSUE_KEY
              artifacts:
                  - junit-results.xml
              image: checkmarx/kics:latest
        - step:
            name: Validate Packer
            script:
              - cd packer
              - packer init .
              - packer validate .
            image: hashicorp/packer:latest
        - step:
            name: Validate Terraform
            script:
              - cd terraform
              - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
              - export AWS_SECRET=$AWS_SECRET
              - terraform init
              - terraform validate
    main:
        - step:
            name: Build AMI
            deployment: Production
            script:
              - cd packer
              - packer init .
              - packer build .
            image: hashicorp/packer:latest
        - step:
            name: Deploy infra
            deployment: Production
            trigger: manual
            script:
              - cd terraform
              - terraform init
              - terraform plan
              - terraform apply -auto-approve

